Credit Card Fraud Detection

1. shape 
2. info 
3. Drop uneccessary features 
4. check for duplicates 
5. check for null values 
6. Scale if necessary 
7. check if the data is imbalanced in case of supervised learning 
8. train test split (even validation split if necessary) 
9. Model Architecture 
10. Performance Metrics 
11. Deployment

In [204]:
import numpy as np 
import pandas as pd 
df=pd.read_csv('creditcard.csv')
pd.options.display.max_columns=None
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [205]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,-1.593105,2.711941,-0.689256,4.626942,-0.924459,1.107641,1.991691,0.510632,-0.682920,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,-0.150189,0.915802,1.214756,-0.675143,1.164931,-0.711757,-0.025693,-1.221179,-1.545556,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,0.411614,0.063119,-0.183699,-0.510602,1.329284,0.140716,0.313502,0.395652,-0.577252,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,-1.933849,-0.962886,-1.042082,0.449624,1.962563,-0.608577,0.509928,1.113981,2.897849,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,-1.040458,-0.031513,-0.188093,-0.084316,0.041333,-0.302620,-0.660377,0.167430,-0.256117,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [206]:
df.shape

(284807, 31)

In [207]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [208]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
df['Amount']=sc.fit_transform(pd.DataFrame(df['Amount'])) 
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244964,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342475,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.160686,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.140534,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073403,0

In [209]:
df.drop('Time',axis=1,inplace=True)

In [210]:
df.duplicated().any()

True

In [211]:
df = df.drop_duplicates()

In [212]:
df.duplicated().any()

False

In [213]:
df.shape

(275663, 30)

In [214]:
x=df.drop('Class',axis=1)
y=df['Class']

In [215]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [216]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

In [217]:
classifier ={ 
        "Logistic Regression" : LogisticRegression() ,
        "Decision Tree Classifier" : DecisionTreeClassifier() ,        
        "Naive Bayes" : GaussianNB()
    }

In [218]:
for name,mod in classifier.items(): 
    print(f"____________ {name}______________")
    mod.fit(x_train,y_train)
    y_pred=mod.predict(x_test)
    print(f"Accuracy Score : {accuracy_score(y_test,y_pred)}")
    print(f"Precision Score : {precision_score(y_test,y_pred)}")
    print(f"Recall Score : {recall_score(y_test,y_pred)}")
    print(f"F1 Score : {f1_score(y_test,y_pred)}")

____________ Logistic Regression______________
Accuracy Score : 0.9992200678359603
Precision Score : 0.8870967741935484
Recall Score : 0.6043956043956044
F1 Score : 0.718954248366013
____________ Decision Tree Classifier______________
Accuracy Score : 0.9990024123483213
Precision Score : 0.6764705882352942
Recall Score : 0.7582417582417582
F1 Score : 0.7150259067357514
____________ Naive Bayes______________
Accuracy Score : 0.9781618994068888
Precision Score : 0.057279236276849645
Recall Score : 0.7912087912087912
F1 Score : 0.10682492581602375

In [219]:
#Checking if the data is imbalanced 
df['Class'].value_counts()
#Yes its an imbalanced dataset

0    275190
1       473
Name: Class, dtype: int64

In [220]:
valid=df[df['Class']==0]
fraud=df[df['Class']==1]
print(f"{valid.shape}")
print(f"{fraud.shape}")

(275190, 30)
(473, 30)

In [221]:
valid_undersampling = valid.sample(len(fraud))
print(valid_undersampling.shape)

(473, 30)

In [222]:
df1=pd.concat([valid_undersampling,fraud],ignore_index=True)
df1.shape

(946, 30)

In [223]:
x=df1.drop('Class',axis=1)
y=df1['Class']

In [224]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [225]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

In [226]:
classifier ={ 
        "Logistic Regression" : LogisticRegression() ,
        "Decision Tree Classifier" : DecisionTreeClassifier() , 
        "Naive Bayes" : GaussianNB()    
    }

In [227]:
for name,mod in classifier.items(): 
    print(f"____________ {name}______________")
    mod.fit(x_train,y_train)
    y_pred=mod.predict(x_test)
    print(f"Accuracy Score : {accuracy_score(y_test,y_pred)}")
    print(f"Precision Score : {precision_score(y_test,y_pred)}")
    print(f"Recall Score : {recall_score(y_test,y_pred)}")
    print(f"F1 Score : {f1_score(y_test,y_pred)}")

____________ Logistic Regression______________
Accuracy Score : 0.9263157894736842
Precision Score : 0.94
Recall Score : 0.9215686274509803
F1 Score : 0.9306930693069307
____________ Decision Tree Classifier______________
Accuracy Score : 0.868421052631579
Precision Score : 0.8468468468468469
Recall Score : 0.9215686274509803
F1 Score : 0.8826291079812206
____________ Naive Bayes______________
Accuracy Score : 0.9
Precision Score : 0.946236559139785
Recall Score : 0.8627450980392157
F1 Score : 0.9025641025641027

In [228]:
from imblearn.over_sampling import SMOTE

In [229]:
x=df.drop('Class',axis=1)
y=df['Class']

In [230]:
x,y=SMOTE().fit_resample(x,y)

In [231]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [232]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

In [233]:
classifier ={ 
        "Logistic Regression" : LogisticRegression() ,
        "Decision Tree Classifier" : DecisionTreeClassifier() , 
        "Naive Bayes" : GaussianNB()       
    }

In [234]:
for name,mod in classifier.items(): 
    print(f"____________ {name}______________")
    mod.fit(x_train,y_train)
    y_pred=mod.predict(x_test)
    print(f"Accuracy Score : {accuracy_score(y_test,y_pred)}")
    print(f"Precision Score : {precision_score(y_test,y_pred)}")
    print(f"Recall Score : {recall_score(y_test,y_pred)}")
    print(f"F1 Score : {f1_score(y_test,y_pred)}")

____________ Logistic Regression______________
Accuracy Score : 0.9441931029470547
Precision Score : 0.9728997289972899
Recall Score : 0.9137683399087323
F1 Score : 0.9424073952542119
____________ Decision Tree Classifier______________
Accuracy Score : 0.9982557505723318
Precision Score : 0.9975671308484177
Recall Score : 0.9989455120629784
F1 Score : 0.9982558456423394
____________ Naive Bayes______________
Accuracy Score : 0.9110614484537956
Precision Score : 0.9721392619201771
Recall Score : 0.8462629311128483
F1 Score : 0.9048442906574394